### ISSUE TITLE
Custom DS920

### ISSUE THREAD

**Issue by xobo219** [Xiao-x7/Redpill_Build#10]
{  
    
    "extra_cmdline": {
        "pid": "0x5583",
        "vid": "0x0781",
        "sn": "2040SBRD42CP2",
        "mac1": "9009D01B7505",
        "mac2": "C4834F275ACC",
        "netif_num": 2
      },
      "driver":"https://raw.githubusercontent.com/wjz304/rp-ext/master/modules/r8125/rpext-index.json",
      "dts":"https://raw.githubusercontent.com/Xiao-x7/Redpill_Build/main/dts/yunxingB250_ds920p.dts"       
      
    
}

**Comment by Xiao-x7** [comment]
xobo219 您好.
您自定义的 DS920+ 版本：7.2.0-64570 已开始构建完成. 请前往下面的 URL 查看详细信息.
> https://github.com/Xiao-x7/Redpill_Build/actions/runs/6012176487
----
