### ISSUE TITLE
DS920

### ISSUE THREAD

**Issue by xobo219** [Xiao-x7/Redpill_Build#8]
{  
    
    "extra_cmdline": {
        "pid": "0x5571",
        "vid": "0x0781",
        "sn": "2040SBRD42CP2",
        "mac1": "9009D01B7505",
        "mac2": "C4834F275ACC",
        "netif_num": 2
      },
      "driver":"https://raw.githubusercontent.com/wjz304/rp-ext/master/modules/r8125/rpext-index.json,
                https://raw.githubusercontent.com/wjz304/rp-ext/main/modules/igc/rpext-index.json",
      "dts":"https://github.com/chenxudong2020/Redpill_Build/raw/master/dts/UNAS_T401P_ds920p.dts.txt"       
      
    
}

**Comment by Xiao-x7** [comment]
分析 title 和 body 内容 ..
> https://github.com/Xiao-x7/Redpill_Build/actions/runs/6012019296
----

**Comment by Xiao-x7** [comment]
超过3天暂时没时间处理，关闭issue
